Project_62133508/Areas/Admin/Controllers/QuanLyDanhMucSanPham_62133508Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using Model.EF;
using Project_62133508.Common;
using PagedList;


namespace Project_62133508.Areas.Admin.Controllers
{
    public class QuanLyDanhMucSanPham_62133508Controller : Controller
    {
        //
        // GET: /Admin/QuanLyDanhMucSanPham_62133508/

        public ActionResult Index(string searchString, int page = 1, int pageSize = 5)
        {
            var dao = new DanhMucSanPhamDAO();
            var model = dao.ListAll(searchString, page, pageSize);
            ViewBag.searchstring = searchString;
            return View(model);
        }
        public ActionResult ChoDuyet(string searchString, int page = 1, int pageSize = 5)
        {
            var dao = new DanhMucSanPhamDAO();
            var model = dao.ChoDuyet(searchString, page, pageSize);
            ViewBag.searchstring = searchString;
            return View(model);
        }




        [HttpGet]
        public ActionResult ThemDanhMuc()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemDanhMuc(DANHMUCSANPHAM cs)
        {
            DANHMUCSANPHAM ds = new DANHMUCSANPHAM();
            ds.IDCha = cs.IDCha;
            ds.TenDanhMuc = cs.TenDanhMuc;
            ds.Metatitle = RewriteURL.RewriteUrl(cs.TenDanhMuc);
            ds.NgayTao = DateTime.Now;
            ds.NguoiTao = UserInfo.Username;
            ds.TrangThai = 0;
            var dao = new DanhMucSanPhamDAO();
            dao.ThemDanhMuc(ds);
            return RedirectToAction("ChoDuyet");
        }
    }
}

Project_62133508/Areas/Admin/Views/QuanLyDanhMucSanPham_62133508/ChoDuyet.cshtml
@model PagedList.IPagedList<Model.EF.DANHMUCSANPHAM>
@using PagedList.Mvc;



@{
    ViewBag.Title = "Chờ duyệt danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@section sectionhead{
    <style>
        th {
            text-align: center;
        }

        td.chucnang {
            text-align: center;
        }
    </style>
}



<div class="=row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    DANH SÁCH DANH MỤC CHỜ DUYỆT
                </h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                @using (Html.BeginForm("ChoDuyet", "QuanLyDanhMucSanPham_62133508", FormMethod.Get))
                {
                    <div class="row" style="padding-bottom: 10px!important">
                        <div class="col-lg-8">
                            <div class="input-group margin">
                                <input type="text" class="form-control" value="@ViewBag.SearchString" name="searchString" placeholder="Nhập tên danh mục hoặc danh mục cha để tìm kiếm...">
                                <span class="input-group-btn">
                                    <button class="btn btn-info btn-flat" type="submit">Tìm</button>
                                </span>
                            </div>
                        </div>
                    </div>
                }
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Mã danh mục</th>
                                <th>Tên danh mục</th>
                                <th>Mã cha</th>
                                <th>Ngày tạo</th>
                                <th>Người tạo</th>
                                <th>Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID">
                                    <td>
                                        @item.ID
                                    </td>
                                    <td class="tb_tenbanghi">
                                        @item.TenDanhMuc
                                    </td>
                                    <td>
                                        @item.IDCha
                                    </td>
                                    <td>@item.NgayTao</td>
                                    <td> @item.NguoiTao</td>
                                    <td>
                                        @*<a href="/Admin/ProductManager/@item.Metatitle-@item.ID" class="clink_llll" title="Bỏ duyệt bài đăng này">Bỏ active</a>*@
                                        @Ajax.ActionLink("Duyệt", "Duyet", new { @id = item.ID }, new AjaxOptions
                                            {
                                                Confirm = "Bạn có chắc chắn muốn duyệt danh mục này?",
                                                OnComplete = "$('#row_" + @item.ID + "').fadeOut(300)",
                                                HttpMethod = "Post"
                                            }, new { @class = "clink_rrrr", @title = "Duyệt danh mục này", area = "Admin" })
                                        <br />
                                        <a href="/Admin/QuanLyDanhMucSanPham_62133508/CapNhat/@item.ID">Cập nhật</a>
                                        <br />
                                        <a href="/Admin/QuanLySanPham_62133508/Khoa/@item.ID">Khóa</a>
                                        @*@Html.ActionLink("Cập nhật", "CapNhat", "QuanLySanPham_62133508", new {@id=item.ID})*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>


                    @Html.PagedListPager(Model, page => Url.Action("ChoDuyet", new { page, @searchString = @ViewBag.searchstring }))
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>

Project_62133508/Areas/Admin/Views/QuanLyDanhMucSanPham_62133508/Index.cshtml
@model PagedList.IPagedList<Model.EF.DANHMUCSANPHAM>
@using PagedList.Mvc;



@{
    ViewBag.Title = "Đã duyệt danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@section sectionhead{
    <style>
        th {
            text-align: center;
        }

        td.chucnang {
            text-align: center;
        }
    </style>
}



<div class="=row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    DANH SÁCH DANH MỤC ĐÃ DUYỆT
                </h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                @using (Html.BeginForm("Index", "QuanLyDanhMucSanPham_62133508", FormMethod.Get))
                {
                    <div class="row" style="padding-bottom: 10px!important">
                        <div class="col-lg-8">
                            <div class="input-group margin">
                                <input type="text" class="form-control" value="@ViewBag.SearchString" name="searchString" placeholder="Nhập tên danh mục hoặc danh mục cha để tìm kiếm...">
                                <span class="input-group-btn">
                                    <button class="btn btn-info btn-flat" type="submit">Tìm</button>
                                </span>
                            </div>
                        </div>
                    </div>
                }
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Mã danh mục</th>
                                <th>Tên danh mục</th>
                                <th>Mã cha</th>
                                <th>Ngày tạo</th>
                                <th>Người tạo</th>
                                <th>Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID">
                                    <td>
                                        @item.ID
                                    </td>
                                    <td class="tb_tenbanghi">
                                       @item.TenDanhMuc
                                    </td>
                                    <td>
                                        @item.IDCha
                                    </td>
                                    <td>@item.NgayTao</td>
                                    <td> @item.NguoiTao</td>
                                    <td>
                                        @*<a href="/Admin/ProductManager/@item.Metatitle-@item.ID" class="clink_llll" title="Bỏ duyệt bài đăng này">Bỏ active</a>*@
                                        @Ajax.ActionLink("Bỏ Duyệt", "BoDuyet", new { @id = item.ID }, new AjaxOptions
                                            {
                                                Confirm = "Bạn có chắc chắn muốn bỏ duyệt danh mục này?",
                                                OnComplete = "$('#row_" + @item.ID + "').fadeOut(300)",
                                                HttpMethod = "Post"
                                            }, new { @class = "clink_rrrr", @title = "Bỏ duyệt danh mục này", area = "Admin" })

                                        @*@Html.ActionLink("Cập nhật", "CapNhat", "QuanLySanPham_62133508", new {@id=item.ID})*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>


                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.searchstring }))
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>

Project_62133508/Areas/Admin/Views/QuanLyDanhMucSanPham_62133508/ThemDanhMuc.cshtml
@model Model.EF.DANHMUCSANPHAM

@{
    ViewBag.Title = "ThemDanhMuc";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section sectionHead{

    <style>
        .form-group {
            margin-bottom: 10px !important;
            clear: both;
            min-height: 35px;
            position: relative;
            padding-bottom: 5px !important;
        }



        .form-control123 {
            display: block;
            width: 60%;
            height: 34px;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857143;
            color: #555;
            background-color: #fff;
            background-image: none;
            border: 1px solid #ccc;
            border-radius: 4px;
            -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
            box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
            -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
            -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
            float: left;
            margin-right: 10px;
        }



        .form-group1122 {
            clear: both;
            padding-top: 10px;
            text-align: center;
        }


        #cke_txtnoidung {
            margin-bottom: 10px;
        }



        .form-group {
            padding-bottom: 25px !important;
        }
    </style>

}


@section sectiontitleheader{
    THÊM DANH MỤC SẢN PHẨM
}




@using (Html.BeginForm("ThemDanhMuc", "QuanLyDanhMucSanPham_62133508", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="form-group">
            @Html.LabelFor(model => model.TenDanhMuc, htmlAttributes: new { @class = "control-laber col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenDanhMuc, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenDanhMuc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDCha, htmlAttributes: new { @class = "control-laber col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.IDCha, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDCha)
            </div>
        </div>
        <br />
        <center>
            <input type="submit" class="btn btn-danger" value="Thêm danh mục">
        </center>
    </fieldset>
}